image: lts2epfl/sadview

cache:
  key: "$CI_BUILD_REF_NAME"
  paths:
    - node_modules/

variables:
  GIT_SSL_NO_VERIFY: "1"

pages:
  script:
    - yarn install
    - yarn build --mode=production
    - yarn layout -s $S3CFG_JSON -i twitter/results -o out -m FA2 -n 500 $EXTRA_PARAMS

  artifacts:
    paths:
      - public

build package:
  stage: build
  script:
    - yarn install
    - yarn build --mode=production
    - echo "//gitlab.switch.ch/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}">.npmrc
    - npm publish
