

cache:
  key: "$CI_BUILD_REF_NAME"
  paths:
    - node_modules/

variables:
  GIT_SSL_NO_VERIFY: "1"

pages:
  image: lts2epfl/sadview
  script:
    - yarn install
    - yarn build --mode=production
    - yarn layout -s $S3CFG_JSON -i twitter/results -o out -m FA2 -n 500 $EXTRA_PARAMS

  artifacts:
    paths:
      - public

build image:
  image: docker:20.10.3
  stage: build
  services:
    - docker:20.10.3-dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY/imi-sad/sadview-server:latest -f docker-server/Dockerfile .
    - docker push $CI_REGISTRY/imi-sad/sadview-server:latest
