image: node:lts-buster

cache:
  key: "$CI_BUILD_REF_NAME"
  paths:
    - node_modules/


pages:
  before_script:
    - apt-get update && apt-get install -q -y ca-certificates

  script:
    - yarn install
    - yarn build --mode=production
    - yarn layout -s $S3CFG_JSON -i twitter/results -o out -m FA2 -n 500 $EXTRA_PARAMS

  artifacts:
    paths:
      - public

