version: "3.9"
services:
  layout:
    build:
      context: ./
      dockerfile: ./docker-server/Dockerfile
    ports:
      - "8081:8081"
  rabbitmq:
    image: "rabbitmq:latest"
    ports:
      - "5672:5672"
